# Generated by Django 3.2 on 2023-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
